### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Review by SimonMellerin — APPROVED** [review]

**Comment by tituspijean** [comment]
Sorry I've discovered issue 34 afterwards. It should be fixed with the last commit.

---

Mmmmh, actually not? If I run the command manually:

```
sudo -u aeneria php7.4 /var/www/aeneria/bin/console aeneria:pending-action:process-expired
18:29:25 ERROR     [app] Pending Action - Missing parameter 'force', delete action ["user" => 2,"action" => 5]
18:29:25 ERROR     [console] Error thrown while running command "aeneria:pending-action:process-expired". Message: "L'action n'a pas de paramètre 'force'" ["exception" => InvalidArgumentException { …},"command" => "aeneria:pending-action:process-expired","message" => "L'action n'a pas de paramètre 'force'"]

In PendingActionService.php line 216:

  L'action n'a pas de paramètre 'force'


aeneria:pending-action:process-expired
```

What do you think?

**Comment by SimonMellerin** [comment]
I checked  thisblast commit, seems good to me ;)

Thanks for your work !

Simon

**Comment by tituspijean** [comment]
The new cronjob command returns an error (also when run manually), cf. above. What do you think about it @SimonMellerin?

**Comment by SimonMellerin** [comment]
Ah sorry !

Do you have this error on your own instance ? 

Do this error  keeps to appear when you run it successively ?

This error comes from an old bug, some actions from UI lead to register "pending action" in database. This command should process these pending actions. But, for a time, there was a bug, a particular action was registered in database with the wrong option leading to this error message. (or maybe this bug is still present ?)

Normally, these wrongly registered actions should be deleted after the message appears.

**Comment by tituspijean** [comment]
I got the issue on my own instance every 15 in last night between 20:30 and 02:15 (the cronjob sends me emails with its output, it helps me debug), but it seems to have finally have stopped now. :) It was happening with the cronjob and also when run manually, not anymore.

**Comment by SimonMellerin** [comment]
arff ok, may be you had a lot of job waiting to be launch :grimacing: 

I will check if it's fixed soon, I'm not sure it is...

**Pull request merged**
